---
- hosts: "prodservers"
  become: yes
  vars_files:
    - varsprod.yml

  tasks:
    - name: Update nodejs package

      shell: curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -

    - name: Install nodejs
      apt:
        name: nodejs
        state: present

    - name: Npm initialization
      shell: npm init -y
      args:
        chdir: "{{ deploy_directory }}/"

    - name: Install node dependencies
      shell: npm install
      args:
        chdir: "{{ deploy_directory }}/"
        

    - name: Create environment variables file
      copy:
        dest: "{{ deploy_directory }}/.env"
        content: |
          # Host configuration
          PORT={{ http_port }}
          HOST=0.0.0.0

          HOST_URL=http://{{ public_ip }}:{{ http_port }}
          COOKIE_ENCRYPT_PWD=superAwesomePasswordStringThatIsAtLeast32CharactersLong!
          NODE_ENV=development

          # Okta configuration
          OKTA_ORG_URL={{ okta_org_url }}
          OKTA_CLIENT_ID={{ okta_client_id }}
          OKTA_CLIENT_SECRET={{ okta_client_secret }}

          # Postgres
          PGHOST={{db_host}}
          PGUSERNAME={{ pg_username }}
          PGDATABASE={{ pg_database }}
          PGPASSWORD={{ pg_password }}
          PGPORT=5432

    - name: Database initialization
      shell: npm run initdb
      async: 30
      poll: 0
      args:
        chdir: "{{ deploy_directory }}/"

    - name: Install pm2
      shell: npm install pm2@latest -g

    - name: Run application
      shell: pm2 start npm -- run dev && pm2 save && pm2 startup
      args:
        chdir: "{{ deploy_directory }}/"


